Cashtokens WIP
CashScript/cashscript pull request #143
Opened 2023-02-13 19:12 UTC by mr-zwets

2023-02-15 14:21 UTC, rkalis requested changes
Now that Libauth v2 has been integrated, I'm guessing that we'll also need to add a few things about P2SH32 and related updates.

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Errors.ts
> +export class TokensToNonTokenAddress extends Error {
Small nit: can you add an `Error` suffix here, to be consistent with the other error classes?

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      if(typeof tokenDetails != "undefined") recipient.token = tokenDetails;
This seems redundant, since you add  `tokenDetails` to the initial `recipient` and then add it again if it's not `undefined`.

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      validateRecipient(recipient);
This is already handled in the `this.to([recipient]);` call below.

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +    const netBalanceTokens: any = {};
Type can be `Record<string, bigint>`

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      if(typeof input.token === "undefined") continue;
Using `typeof input.token === 'undefined'` is more JS style. I think in TS it's more idiomatic to just say `input.token === undefined` or `!input.token` depending on how strict you want your check to be. Same for other places where you use the same pattern.

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      for(const tokenBalance of netBalanceTokens){
`netBalanceTokens` is an object, so we cannot use `for ... of`.

Perhaps this can be replaced with something like:

```
Object.entries(netBalanceTokens).forEach(([category, balance]) => {
  ...
})
```

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +            amount : BigInt(-tokenBalance.amount)
Why is this made to be negative?

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +            category : tokenBalance.category,
`tokenBalance.amount` and `tokenBalance.category` are `undefined`, but changing to something like the comment on L320 would require a rewrite of this already.

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +          throw new Error(`Insufficient token balance.`);
We should probably add *which* token doesn't have enough balance.

2023-02-15 14:21 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      // Compare nfts in- and outputs, check if inputs have nfts corresponsing to outputs
The whole NFT change section is really difficult to follow. I can sympathise with that because if I'm being honest the "regular" BCH input selection + change calculation that I wrote is already some of the least readable code in the code base, and it's much more complex for NFTs of course.

I've tried to think of ways to simplify this, but I'm not entirely sure yet either. If you could give this point some more thought that would be much appreciated. In any case I think we'll need to add some really good edge case tests for this to make sure things are working as expected.

2023-02-17 18:29 UTC, mr-zwets commented on packages/cashscript/src/Errors.ts
> +export class TokensToNonTokenAddress extends Error {
sure

2023-02-17 18:38 UTC, mr-zwets commented on packages/cashscript/src/Transaction.ts
> +      if(typeof tokenDetails != "undefined") recipient.token = tokenDetails;
ah thanks for catching this!

Not sure which is better to have the key regardless or only when it actually contains a token object.
I made the token key optional in the types for `Recipient` & `Output`
Relevant for this code for example
```
if ('token' in recipient) {
    if(!isTokenAddress(recipient.to)){
      throw new TokensToNonTokenAddress(recipient.to);
    }
  }
```
can change it to `if(recipient.token){` if the value is undefined for non token holding recipients...

2023-02-17 18:40 UTC, mr-zwets commented on packages/cashscript/src/Transaction.ts
> +      validateRecipient(recipient);
ah makes sense

2023-02-17 18:45 UTC, mr-zwets commented on packages/cashscript/src/Transaction.ts
> +    const netBalanceTokens: any = {};
awesome thanks! I knew type any wasn't good practice but didn't know this is the correct approach!

2023-02-20 11:45 UTC, mr-zwets commented on packages/cashscript/src/Transaction.ts
> +      for(const tokenBalance of netBalanceTokens){
right 👍 could also keep the for(... of ...) with
`for (const [category, balance] of Object.entries(netBalanceTokens)) {`

2023-02-20 11:53 UTC, mr-zwets commented on packages/cashscript/src/Transaction.ts
> +            amount : BigInt(-tokenBalance.amount)
I think I added the minus sign when the object used to hold output balances and subtracted inputs so change would be a negative number. So it's there still by mistake 😅

2023-02-20 12:07 UTC, mr-zwets commented on packages/cashscript/src/Transaction.ts
> +      // Compare nfts in- and outputs, check if inputs have nfts corresponsing to outputs
> If you could give this point some more thought that would be much appreciated. In any case I think we'll need to add some really good edge case tests for this to make sure things are working as expected.

Sure will give it some more thought. Do you agree on the high level that it's correct to keep a  `netBalanceTokens` object for fungible tokens with tokenId as key and amount as value (where inputs are added to the amount and outputs subtracted). And that for NFTs a list of outputs is kept and checked against a list of NFT inputs?

I agree edge case testing is really important for this part of the code

2023-02-20 16:06 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      if(typeof tokenDetails != "undefined") recipient.token = tokenDetails;
I think it's probably fine to have the key regardless (and just have the value be undefined). And then like you said, we should use `if (recipient.token) { ... }`.

2023-02-20 16:08 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      for(const tokenBalance of netBalanceTokens){
Yeah you can also keep the `for ... of` in that case 👌

2023-02-20 16:09 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      // Compare nfts in- and outputs, check if inputs have nfts corresponsing to outputs
Yeah I think overall that kind of approach seems like the way to go 👌

2023-02-21 15:24 UTC, rkalis commented on packages/cashscript/src/Transaction.ts
> +      for(const tokenBalance of netBalanceTokens){
I just checked out the code locally, and linting rules state that using `continue` is forbidden. I generally try to keep the eslint config pretty close to the airbnb styleguide config (can be checked in `.eslintrc.cjs`). 

In cases like this I don't see a great reason for why we'd need to make an exception here, even though I'm not sure about the rationale behind airbnb's decision to block `continue` statements 🤷‍♂️

So in that case we need to replace the `for ... of` loops with `array.forEach(() => {})` and use `return` statements where you use `continue` statements now. Most other linting issues can just get fixed by running `yarn lint --fix` in the separate packages.

2023-03-22 11:40 UTC, rkalis commented
There are still some open linting issues and we still have to add some more tests. But we'll do that before merging `next` into `master`.

2023-03-22 11:41 UTC, merged