docs: typos and grammar (1)
CashScript/cashscript pull request #194
Opened 2024-06-07 16:53 UTC by fredericAerts

2024-06-11 07:46 UTC, mr-zwets commented
Thanks for the PR! 🙏  

You let me know that you'll still be going over the SDK docs to check for typos and grammar.
We'll wait to merge the PR for your full check-up on the docs! 😄

2024-06-14 10:34 UTC, fredericAerts commented
I've gone through SDK section and committed changes. Check-up on the docs done for my part.

2024-06-18 08:13 UTC, rkalis requested changes
Hey @fredericAerts , thanks so much for the contribution! There's just the one place with a `,.`, besides that everything looks great. If you could edit that one issue we'll get this merged in.

2024-06-18 08:13 UTC, rkalis commented on website/docs/sdk/instantiation.md
> +The `Contract` class is used to represent a CashScript contract in a JavaScript object. These objects can be used to retrieve information such as the contract's address and balance,. They can also be
Small extra comma here.

2024-06-18 08:30 UTC, fredericAerts commented on website/docs/sdk/instantiation.md
> +The `Contract` class is used to represent a CashScript contract in a JavaScript object. These objects can be used to retrieve information such as the contract's address and balance,. They can also be
Nice that you noticed that one!

2024-06-18 10:10 UTC, rkalis commented on website/docs/sdk/instantiation.md
> +The `Contract` class is used to represent a CashScript contract in a JavaScript object. These objects can be used to retrieve information such as the contract's address and balance,. They can also be
Thanks for the quick fix!

2024-06-18 10:10 UTC, rkalis approved these changes

2024-06-18 10:10 UTC, merged

2024-06-18 10:11 UTC, rkalis commented
Thank you again for the contribution!